### PR TITLE
Extended functionality/compatibility: 1D, non-default domains, clipping

### PR DESCRIPTION
**Pull request by opcode81**
Changes (see also individual commits):

1. Use LUT implementations from the colour library, replacing the class CubeLUT. This adds **support for 1-dimensional cube LUTs**, among other things. This change addresses issue #1.
2. Add **support for non-default domains** (i.e. domains that are not [0,1]).
3. Add **option to clip LUT values to the domain's bounds**, which solves issues with some commercial LUTs, which may have been exported in a strange way. For example, it makes LUTs from LUTs.Store applicable, which contain negative values that result in strange artifacts when applied using pycubelut/colours.
4. Allow output filename composition and output image quality to be configured.

### CODE REVIEW

**Comment by yoonsikp** [comment]
Thanks for the PR! I will test it out this weekend.

**Comment by yoonsikp** [comment]
@opcode81 I'm wondering if you could analyze the performance regressions? I'm getting approximately 1.7x to 2.0x slowdown. Otherwise the image looks the same.

**Comment by opcode81** [comment]
@yoonsikp, I did a quick analysis using a single thread where I applied 183 LUTs to a single HD image.

I found that, on average, LUT application is roughly equivalent (2% difference), while the construction of LUT objects now takes 94% longer. The LUT construction in the colour library is, apparently, more involved.

When multiprocessing comes into play, there could be other effects, e.g. the size of the pickled LUT objects could be different, causing further differences in runtime behaviour.

Personally, I don't think these differences are anything to worry about. The colour library's LUT objects add some flexibility, so I think it's worth it. It's highly unlikely that anybody is using pycubelut in a scenario where execution times really matter. If maximum performance was of the utmost importance, we wouldn't be using Python in the first place, right?

**Comment by yoonsikp** [comment]
Thank you for the analysis! I agree, the differences aren't as bad is I thought. Seeing as loading the luts is a one time operation during multiprocessing, this will be acceptable.

**Pull request merged**
